const fs = require('fs');
const path = require('path');
const mysql = require('mysql2/promise');

class LocalStore {
  constructor(file) {
    this.file = file;
    this.data = { users: [], friendships: [], conversations: [], conversationMembers: [], messages: [], summaries: [], notifications: [], passwordResets: [], auditLogs: [], userBlocks: [], reports: [], meetingSessions: [], meetingParticipants: [], meetingTranscripts: [], meetingSummaries: [], counters: {} };
    this.load();
  }
  load(){
    try { if (fs.existsSync(this.file)) this.data = JSON.parse(fs.readFileSync(this.file,'utf8')); this.data.userBlocks=this.data.userBlocks||[]; this.data.reports=this.data.reports||[]; this.data.meetingSessions=this.data.meetingSessions||[]; this.data.meetingParticipants=this.data.meetingParticipants||[]; this.data.meetingTranscripts=this.data.meetingTranscripts||[]; this.data.meetingSummaries=this.data.meetingSummaries||[]; this.data.counters=this.data.counters||{}; } catch(e){ console.error('Local DB load error:', e.message); }
  }
  save(){ fs.mkdirSync(path.dirname(this.file), {recursive:true}); fs.writeFileSync(this.file, JSON.stringify(this.data,null,2)); }
  next(key){ this.data.counters[key]=(this.data.counters[key]||0)+1; return this.data.counters[key]; }
  cleanUser(u){ if(!u) return null; const {password_hash,...safe}=u; return safe; }
  async createUser({username,email,password_hash}){
    if(this.data.users.some(u=>u.email.toLowerCase()===email.toLowerCase())) throw new Error('EMAIL_EXISTS');
    if(this.data.users.some(u=>u.username.toLowerCase()===username.toLowerCase())) throw new Error('USERNAME_EXISTS');
    const u={id:this.next('users'),username,email,password_hash,avatar_url:null,bio:'',status:'active',created_at:new Date().toISOString()}; this.data.users.push(u); this.save(); return this.cleanUser(u);
  }
  async findUserByLogin(id){ return this.data.users.find(u=>u.email.toLowerCase()===String(id).toLowerCase()||u.username.toLowerCase()===String(id).toLowerCase())||null; }
  async findUserByEmail(email){ return this.data.users.find(u=>u.email.toLowerCase()===String(email).toLowerCase())||null; }
  async getUser(id){ return this.cleanUser(this.data.users.find(u=>u.id===Number(id))); }
  async updateProfile(id,{username,bio,avatar_url}){
    const u=this.data.users.find(u=>u.id===Number(id)); if(!u) return null;
    if(username && this.data.users.some(x=>x.id!==u.id&&x.username.toLowerCase()===username.toLowerCase())) throw new Error('USERNAME_EXISTS');
    if(username)u.username=username; if(bio!==undefined)u.bio=bio; if(avatar_url)u.avatar_url=avatar_url; this.save(); return this.cleanUser(u);
  }
  async updatePassword(id,password_hash){ const u=this.data.users.find(u=>u.id===Number(id)); if(!u)return false; u.password_hash=password_hash; this.save(); return true; }
  async searchUsers(query,currentId){ const q=String(query||'').toLowerCase(); return this.data.users.filter(u=>u.id!==Number(currentId)&&u.status==='active'&&(u.username.toLowerCase().includes(q)||u.email.toLowerCase().includes(q))).slice(0,20).map(u=>this.cleanUser(u)); }
  async createFriendRequest(sender,receiver){
    sender=Number(sender);receiver=Number(receiver); if(sender===receiver)throw new Error('SELF');
    const accepted=this.data.friendships.find(f=>f.status==='accepted'&&((f.sender_id===sender&&f.receiver_id===receiver)||(f.sender_id===receiver&&f.receiver_id===sender))); if(accepted)throw new Error('ALREADY_FRIENDS');
    const pending=this.data.friendships.find(f=>f.status==='pending'&&((f.sender_id===sender&&f.receiver_id===receiver)||(f.sender_id===receiver&&f.receiver_id===sender))); if(pending)throw new Error('REQUEST_EXISTS');
    const f={id:this.next('friendships'),sender_id:sender,receiver_id:receiver,status:'pending',created_at:new Date().toISOString()}; this.data.friendships.push(f); this.save(); return f;
  }
  async incomingRequests(userId){ return this.data.friendships.filter(f=>f.receiver_id===Number(userId)&&f.status==='pending').map(f=>({...f,sender:this.cleanUser(this.data.users.find(u=>u.id===f.sender_id))})); }
  async respondFriendRequest(id,userId,status){ const f=this.data.friendships.find(f=>f.id===Number(id)&&f.receiver_id===Number(userId)&&f.status==='pending'); if(!f)return null; f.status=status; this.save(); return f; }
  async friends(userId){ const id=Number(userId); return this.data.friendships.filter(f=>f.status==='accepted'&&(f.sender_id===id||f.receiver_id===id)).map(f=>{const other=f.sender_id===id?f.receiver_id:f.sender_id;if(this.data.userBlocks.some(x=>(x.blocker_id===id&&x.blocked_user_id===other)||(x.blocker_id===other&&x.blocked_user_id===id)))return null;return this.cleanUser(this.data.users.find(u=>u.id===other));}).filter(Boolean); }
  async createOrGetDirectConversation(a,b){
    a=Number(a);b=Number(b);
    for(const c of this.data.conversations.filter(c=>c.type==='direct')){
      const members=this.data.conversationMembers.filter(m=>m.conversation_id===c.id).map(m=>m.user_id).sort((x,y)=>x-y); if(members.length===2&&members[0]===Math.min(a,b)&&members[1]===Math.max(a,b))return c;
    }
    const c={id:this.next('conversations'),title:null,type:'direct',created_at:new Date().toISOString()}; this.data.conversations.push(c); this.data.conversationMembers.push({conversation_id:c.id,user_id:a,role:'member'},{conversation_id:c.id,user_id:b,role:'member'}); this.save(); return c;
  }
  async createGroupConversation(ownerId,title,memberIds){
    ownerId=Number(ownerId); const unique=[...new Set([ownerId,...memberIds.map(Number)])];
    const c={id:this.next('conversations'),title:String(title||'Group').slice(0,150),type:'group',created_at:new Date().toISOString()};
    this.data.conversations.push(c); unique.forEach(uid=>this.data.conversationMembers.push({conversation_id:c.id,user_id:uid,role:uid===ownerId?'admin':'member'})); this.save(); return c;
  }
  async userConversations(userId){
    const id=Number(userId), ids=this.data.conversationMembers.filter(m=>m.user_id===id).map(m=>m.conversation_id);
    return ids.map(cid=>{const c=this.data.conversations.find(x=>x.id===cid); const memberIds=this.data.conversationMembers.filter(m=>m.conversation_id===cid&&m.user_id!==id).map(m=>m.user_id); const others=memberIds.map(uid=>this.cleanUser(this.data.users.find(u=>u.id===uid))).filter(Boolean); const last=[...this.data.messages].reverse().find(m=>m.conversation_id===cid)||null; return {...c,others,lastMessage:last};}).sort((a,b)=>new Date(b.lastMessage?.created_at||b.created_at)-new Date(a.lastMessage?.created_at||a.created_at));
  }
  async isConversationMember(cid,uid){ return this.data.conversationMembers.some(m=>m.conversation_id===Number(cid)&&m.user_id===Number(uid)); }
  async addMessage({conversation_id,sender_id,body,attachment_url}){ const m={id:this.next('messages'),conversation_id:Number(conversation_id),sender_id:Number(sender_id),body:body||'',attachment_url:attachment_url||null,created_at:new Date().toISOString()}; this.data.messages.push(m); this.save(); const user=this.cleanUser(this.data.users.find(u=>u.id===m.sender_id)); return {...m,sender:user,receipt_status:'sent'}; }
  async initMessageReceipts(mid,sender,members){this.data.messageReceipts=this.data.messageReceipts||[];for(const uid of members.filter(x=>Number(x)!==Number(sender)))this.data.messageReceipts.push({message_id:Number(mid),user_id:Number(uid),delivered_at:null,read_at:null});this.save();}
  async markMessageDelivered(mid,uid){this.data.messageReceipts=this.data.messageReceipts||[];const r=this.data.messageReceipts.find(x=>x.message_id===Number(mid)&&x.user_id===Number(uid));if(r&&!r.delivered_at){r.delivered_at=new Date().toISOString();this.save();}return r;}
  async markConversationRead(cid,uid){this.data.messageReceipts=this.data.messageReceipts||[];const mids=new Set(this.data.messages.filter(m=>m.conversation_id===Number(cid)&&m.sender_id!==Number(uid)).map(m=>m.id));const changed=[];for(const r of this.data.messageReceipts){if(r.user_id===Number(uid)&&mids.has(r.message_id)&&!r.read_at){r.delivered_at=r.delivered_at||new Date().toISOString();r.read_at=new Date().toISOString();const m=this.data.messages.find(x=>x.id===r.message_id);changed.push({message_id:r.message_id,sender_id:m?.sender_id});}}this.save();return changed;}
  async getMessages(cid,limit=200,viewerId=null){ return this.data.messages.filter(m=>m.conversation_id===Number(cid)).slice(-limit).map(m=>{const receipts=(this.data.messageReceipts||[]).filter(r=>r.message_id===m.id);const status=receipts.length&&receipts.every(r=>r.read_at)?'read':receipts.some(r=>r.delivered_at)?'delivered':'sent';return {...m,sender:this.cleanUser(this.data.users.find(u=>u.id===m.sender_id)),receipt_status:status};}); }
  async conversationMembers(cid){ return this.data.conversationMembers.filter(m=>m.conversation_id===Number(cid)).map(m=>this.cleanUser(this.data.users.find(u=>u.id===m.user_id))).filter(Boolean); }
  async conversationMemberDetails(cid){ return this.data.conversationMembers.filter(m=>m.conversation_id===Number(cid)).map(m=>{const u=this.cleanUser(this.data.users.find(u=>u.id===m.user_id));return u?{...u,role:m.role||'member'}:null}).filter(Boolean); }
  async addConversationMember(cid,adminId,userId){const admin=this.data.conversationMembers.find(m=>m.conversation_id===Number(cid)&&m.user_id===Number(adminId)&&m.role==='admin');if(!admin)throw new Error('ADMIN_REQUIRED');if(!this.data.conversationMembers.some(m=>m.conversation_id===Number(cid)&&m.user_id===Number(userId)))this.data.conversationMembers.push({conversation_id:Number(cid),user_id:Number(userId),role:'member'});this.save();return true;}
  async removeConversationMember(cid,adminId,userId){const admin=this.data.conversationMembers.find(m=>m.conversation_id===Number(cid)&&m.user_id===Number(adminId)&&m.role==='admin');if(!admin)throw new Error('ADMIN_REQUIRED');if(Number(adminId)===Number(userId))throw new Error('USE_LEAVE');this.data.conversationMembers=this.data.conversationMembers.filter(m=>!(m.conversation_id===Number(cid)&&m.user_id===Number(userId)));this.save();return true;}
  async leaveConversation(cid,userId){const mine=this.data.conversationMembers.find(m=>m.conversation_id===Number(cid)&&m.user_id===Number(userId));if(!mine)return false;if(mine.role==='admin'){const others=this.data.conversationMembers.filter(m=>m.conversation_id===Number(cid)&&m.user_id!==Number(userId));if(others.length)others[0].role='admin';}this.data.conversationMembers=this.data.conversationMembers.filter(m=>!(m.conversation_id===Number(cid)&&m.user_id===Number(userId)));this.save();return true;}
  async markConversationNotifications(uid,cid){this.data.notifications.filter(n=>n.user_id===Number(uid)&&n.type==='message'&&Number(n.payload?.conversationId)===Number(cid)).forEach(n=>n.is_read=true);this.save();}
  async saveSummary(conversation_id,summary){ const s={id:this.next('summaries'),conversation_id:Number(conversation_id),...summary,created_at:new Date().toISOString()}; this.data.summaries.push(s); this.save(); return s; }
  async summariesForUser(uid){ const ids=this.data.conversationMembers.filter(m=>m.user_id===Number(uid)).map(m=>m.conversation_id); return this.data.summaries.filter(s=>ids.includes(s.conversation_id)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)); }
  async addNotification(user_id,type,payload){ const n={id:this.next('notifications'),user_id:Number(user_id),type,payload,is_read:false,created_at:new Date().toISOString()}; this.data.notifications.push(n); this.save(); return n; }
  async notifications(uid){ return this.data.notifications.filter(n=>n.user_id===Number(uid)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)); }
  async markNotifications(uid,types=null){ const allowed=Array.isArray(types)&&types.length?new Set(types):null; this.data.notifications.filter(n=>n.user_id===Number(uid)&&(!allowed||allowed.has(n.type))).forEach(n=>n.is_read=true); this.save(); }
  async addReset(user_id,code_hash,expires_at){ const r={id:this.next('passwordResets'),user_id:Number(user_id),code_hash,expires_at,used:false,created_at:new Date().toISOString()}; this.data.passwordResets.push(r); this.save(); return r; }
  async latestReset(user_id){ return [...this.data.passwordResets].reverse().find(r=>r.user_id===Number(user_id)&&!r.used)||null; }
  async markResetUsed(id){ const r=this.data.passwordResets.find(r=>r.id===Number(id)); if(r){r.used=true;this.save();} }

  async isBlockedEitherWay(a,b){a=Number(a);b=Number(b);return this.data.userBlocks.some(x=>(x.blocker_id===a&&x.blocked_user_id===b)||(x.blocker_id===b&&x.blocked_user_id===a));}
  async blockedIds(uid){uid=Number(uid);return this.data.userBlocks.filter(x=>x.blocker_id===uid).map(x=>x.blocked_user_id);}
  async blockUser(blocker,blocked){blocker=Number(blocker);blocked=Number(blocked);if(blocker===blocked)throw new Error('SELF');if(!this.data.users.some(u=>u.id===blocked&&u.status==='active'))throw new Error('USER_NOT_FOUND');if(!this.data.userBlocks.some(x=>x.blocker_id===blocker&&x.blocked_user_id===blocked))this.data.userBlocks.push({id:this.next('userBlocks'),blocker_id:blocker,blocked_user_id:blocked,created_at:new Date().toISOString()});this.save();return true;}
  async unblockUser(blocker,blocked){blocker=Number(blocker);blocked=Number(blocked);this.data.userBlocks=this.data.userBlocks.filter(x=>!(x.blocker_id===blocker&&x.blocked_user_id===blocked));this.save();return true;}
  async reportUser(reporter,reported,{reason,description,conversation_id=null,message_id=null}){reporter=Number(reporter);reported=Number(reported);if(reporter===reported)throw new Error('SELF');if(!this.data.users.some(u=>u.id===reported))throw new Error('USER_NOT_FOUND');const r={id:this.next('reports'),reporter_id:reporter,reported_user_id:reported,conversation_id:conversation_id?Number(conversation_id):null,message_id:message_id?Number(message_id):null,reason:String(reason||'other').slice(0,60),description:String(description||'').slice(0,1000),status:'open',reviewed_by:null,reviewed_at:null,created_at:new Date().toISOString()};this.data.reports.push(r);this.save();return r;}
  async adminReports(){return [...this.data.reports].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(r=>({...r,reporter:this.cleanUser(this.data.users.find(u=>u.id===r.reporter_id)),reported:this.cleanUser(this.data.users.find(u=>u.id===r.reported_user_id))}));}
  async setReportStatus(id,status,adminEmail){const r=this.data.reports.find(x=>x.id===Number(id));if(!r)return null;r.status=status;r.reviewed_by=adminEmail;r.reviewed_at=new Date().toISOString();this.save();return r;}
  async setUserStatus(id,status){const u=this.data.users.find(x=>x.id===Number(id));if(!u)return null;u.status=status;this.save();return this.cleanUser(u);}
  async adminStats(){ return {users:this.data.users.length,activeUsers:this.data.users.filter(u=>u.status==='active').length,suspendedUsers:this.data.users.filter(u=>u.status==='suspended').length,openReports:this.data.reports.filter(r=>r.status==='open').length,friendships:this.data.friendships.filter(f=>f.status==='accepted').length,conversations:this.data.conversations.length,summaries:this.data.summaries.length}; }
  async adminUsers(){ return this.data.users.map(u=>this.cleanUser(u)); }

  async ensureMeeting(roomId,conversationId=null){roomId=String(roomId||'').slice(0,80);let m=this.data.meetingSessions.find(x=>x.room_id===roomId);if(!m){m={id:this.next('meetingSessions'),room_id:roomId,conversation_id:conversationId?Number(conversationId):null,created_at:new Date().toISOString(),ended_at:null};this.data.meetingSessions.push(m);this.save();}return m;}
  async addMeetingParticipant(meetingId,userId){if(!this.data.meetingParticipants.some(x=>x.meeting_id===Number(meetingId)&&x.user_id===Number(userId)))this.data.meetingParticipants.push({meeting_id:Number(meetingId),user_id:Number(userId),joined_at:new Date().toISOString()});this.save();return true;}
  async isMeetingParticipant(roomId,userId){const m=this.data.meetingSessions.find(x=>x.room_id===String(roomId));return !!(m&&this.data.meetingParticipants.some(x=>x.meeting_id===m.id&&x.user_id===Number(userId)));}
  async saveMeetingTranscript(roomId,{conversation_id=null,speaker_id,speaker_name,language,text}){const m=await this.ensureMeeting(roomId,conversation_id);const t={id:this.next('meetingTranscripts'),meeting_id:m.id,room_id:m.room_id,conversation_id:m.conversation_id,speaker_id:Number(speaker_id),speaker_name:String(speaker_name||'Participant').slice(0,80),language:String(language||'').slice(0,20),text:String(text||'').slice(0,2000),created_at:new Date().toISOString()};this.data.meetingTranscripts.push(t);this.save();return t;}
  async meetingTranscript(roomId,userId){if(!(await this.isMeetingParticipant(roomId,userId)))return null;const m=this.data.meetingSessions.find(x=>x.room_id===String(roomId));return this.data.meetingTranscripts.filter(x=>x.meeting_id===m.id).sort((a,b)=>new Date(a.created_at)-new Date(b.created_at));}
  async saveMeetingSummary(roomId,userId,language,summary){const m=this.data.meetingSessions.find(x=>x.room_id===String(roomId));if(!m||!(await this.isMeetingParticipant(roomId,userId)))throw new Error('NOT_ALLOWED');const x={id:this.next('meetingSummaries'),meeting_id:m.id,room_id:m.room_id,conversation_id:m.conversation_id,requested_by:Number(userId),language,...summary,created_at:new Date().toISOString()};this.data.meetingSummaries.push(x);this.save();return x;}
  async meetingSummariesForUser(uid){const mids=this.data.meetingParticipants.filter(x=>x.user_id===Number(uid)).map(x=>x.meeting_id);return this.data.meetingSummaries.filter(x=>mids.includes(x.meeting_id)).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));}
  async deleteMeetingSummary(id,uid){const x=this.data.meetingSummaries.find(x=>x.id===Number(id));if(!x||!this.data.meetingParticipants.some(p=>p.meeting_id===x.meeting_id&&p.user_id===Number(uid)))return false;this.data.meetingSummaries=this.data.meetingSummaries.filter(x=>x.id!==Number(id));this.save();return true;}
  async clearMeetingTranscript(roomId,uid){if(!(await this.isMeetingParticipant(roomId,uid)))return false;const m=this.data.meetingSessions.find(x=>x.room_id===String(roomId));this.data.meetingTranscripts=this.data.meetingTranscripts.filter(x=>x.meeting_id!==m.id);this.save();return true;}

  async audit(admin_email,action,target_user_id,details){ const a={id:this.next('auditLogs'),admin_email,action,target_user_id:target_user_id||null,details:details||{},created_at:new Date().toISOString()}; this.data.auditLogs.push(a);this.save();return a; }
}

class MySQLStore {
  constructor(pool){this.pool=pool;}
  cleanUser(u){if(!u)return null;const {password_hash,...safe}=u;return safe;}
  async createUser({username,email,password_hash}){try{const [r]=await this.pool.execute('INSERT INTO users(username,email,password_hash) VALUES(?,?,?)',[username,email,password_hash]);return this.getUser(r.insertId);}catch(e){if(e.code==='ER_DUP_ENTRY')throw new Error(String(e.message).includes('email')?'EMAIL_EXISTS':'USERNAME_EXISTS');throw e;}}
  async findUserByLogin(id){const [r]=await this.pool.execute('SELECT * FROM users WHERE email=? OR username=? LIMIT 1',[id,id]);return r[0]||null;}
  async findUserByEmail(email){const [r]=await this.pool.execute('SELECT * FROM users WHERE email=? LIMIT 1',[email]);return r[0]||null;}
  async getUser(id){const [r]=await this.pool.execute('SELECT * FROM users WHERE id=?',[id]);return this.cleanUser(r[0]);}
  async updateProfile(id,{username,bio,avatar_url}){await this.pool.execute('UPDATE users SET username=COALESCE(?,username), bio=?, avatar_url=COALESCE(?,avatar_url) WHERE id=?',[username||null,bio||'',avatar_url||null,id]);return this.getUser(id);}
  async updatePassword(id,password_hash){await this.pool.execute('UPDATE users SET password_hash=? WHERE id=?',[password_hash,id]);return true;}
  async searchUsers(q,currentId){const like=`%${q}%`;const [r]=await this.pool.execute('SELECT id,username,email,avatar_url,bio,status,created_at FROM users WHERE id<>? AND status="active" AND (username LIKE ? OR email LIKE ?) LIMIT 20',[currentId,like,like]);return r;}
  async createFriendRequest(sender,receiver){try{const [r]=await this.pool.execute('INSERT INTO friendships(sender_id,receiver_id,status) VALUES(?,?,"pending")',[sender,receiver]);return {id:r.insertId,sender_id:sender,receiver_id:receiver,status:'pending'};}catch(e){throw new Error('REQUEST_EXISTS');}}
  async incomingRequests(uid){const [r]=await this.pool.execute('SELECT f.*,u.id as u_id,u.username,u.email,u.avatar_url,u.bio,u.status,u.created_at as u_created FROM friendships f JOIN users u ON u.id=f.sender_id WHERE f.receiver_id=? AND f.status="pending" ORDER BY f.created_at DESC',[uid]);return r.map(x=>({id:x.id,sender_id:x.sender_id,receiver_id:x.receiver_id,status:x.status,created_at:x.created_at,sender:{id:x.u_id,username:x.username,email:x.email,avatar_url:x.avatar_url,bio:x.bio,status:x.status,created_at:x.u_created}}));}
  async respondFriendRequest(id,uid,status){const [before]=await this.pool.execute('SELECT * FROM friendships WHERE id=? AND receiver_id=? AND status="pending" LIMIT 1',[id,uid]);if(!before[0])return null;await this.pool.execute('UPDATE friendships SET status=? WHERE id=?',[status,id]);return {...before[0],status};}
  async friends(uid){const [r]=await this.pool.execute('SELECT u.id,u.username,u.email,u.avatar_url,u.bio,u.status,u.created_at FROM friendships f JOIN users u ON u.id=IF(f.sender_id=?,f.receiver_id,f.sender_id) WHERE f.status="accepted" AND (f.sender_id=? OR f.receiver_id=?) AND NOT EXISTS (SELECT 1 FROM user_blocks b WHERE (b.blocker_id=? AND b.blocked_user_id=u.id) OR (b.blocker_id=u.id AND b.blocked_user_id=?))',[uid,uid,uid,uid,uid]);return r;}
  async createOrGetDirectConversation(a,b){const [r]=await this.pool.execute('SELECT c.* FROM conversations c JOIN conversation_members m1 ON m1.conversation_id=c.id AND m1.user_id=? JOIN conversation_members m2 ON m2.conversation_id=c.id AND m2.user_id=? WHERE c.type="direct" LIMIT 1',[a,b]);if(r[0])return r[0];const conn=await this.pool.getConnection();try{await conn.beginTransaction();const [cr]=await conn.execute('INSERT INTO conversations(type) VALUES("direct")');await conn.execute('INSERT INTO conversation_members(conversation_id,user_id) VALUES(?,?),(?,?)',[cr.insertId,a,cr.insertId,b]);await conn.commit();return {id:cr.insertId,type:'direct',created_at:new Date()};}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
  async createGroupConversation(ownerId,title,memberIds){const ids=[...new Set([Number(ownerId),...memberIds.map(Number)])];const conn=await this.pool.getConnection();try{await conn.beginTransaction();const [cr]=await conn.execute('INSERT INTO conversations(title,type) VALUES(?,"group")',[String(title||'Group').slice(0,150)]);for(const uid of ids)await conn.execute('INSERT INTO conversation_members(conversation_id,user_id,role) VALUES(?,?,?)',[cr.insertId,uid,uid===Number(ownerId)?'admin':'member']);await conn.commit();return {id:cr.insertId,title:String(title||'Group').slice(0,150),type:'group',created_at:new Date()};}catch(e){await conn.rollback();throw e;}finally{conn.release();}}
  async userConversations(uid){const [r]=await this.pool.execute('SELECT DISTINCT c.* FROM conversations c JOIN conversation_members cm ON cm.conversation_id=c.id WHERE cm.user_id=? ORDER BY c.created_at DESC',[uid]);for(const c of r){const [o]=await this.pool.execute('SELECT u.id,u.username,u.email,u.avatar_url,u.bio FROM conversation_members cm JOIN users u ON u.id=cm.user_id WHERE cm.conversation_id=? AND cm.user_id<>?',[c.id,uid]);c.others=o;const [lm]=await this.pool.execute('SELECT * FROM messages WHERE conversation_id=? ORDER BY id DESC LIMIT 1',[c.id]);c.lastMessage=lm[0]||null;}return r;}
  async isConversationMember(cid,uid){const [r]=await this.pool.execute('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=?',[cid,uid]);return !!r[0];}
  async addMessage({conversation_id,sender_id,body,attachment_url}){const [r]=await this.pool.execute('INSERT INTO messages(conversation_id,sender_id,body,attachment_url) VALUES(?,?,?,?)',[conversation_id,sender_id,body||'',attachment_url||null]);const [m]=await this.pool.execute('SELECT m.*,u.username,u.avatar_url FROM messages m JOIN users u ON u.id=m.sender_id WHERE m.id=?',[r.insertId]);const x=m[0];return {...x,sender:{id:x.sender_id,username:x.username,avatar_url:x.avatar_url},receipt_status:'sent'};}
  async initMessageReceipts(mid,sender,members){for(const uid of members.filter(x=>Number(x)!==Number(sender)))await this.pool.execute('INSERT IGNORE INTO message_receipts(message_id,user_id) VALUES(?,?)',[mid,uid]);}
  async markMessageDelivered(mid,uid){await this.pool.execute('UPDATE message_receipts SET delivered_at=COALESCE(delivered_at,CURRENT_TIMESTAMP) WHERE message_id=? AND user_id=?',[mid,uid]);}
  async markConversationRead(cid,uid){const [rows]=await this.pool.execute('SELECT mr.message_id,m.sender_id FROM message_receipts mr JOIN messages m ON m.id=mr.message_id WHERE m.conversation_id=? AND mr.user_id=? AND mr.read_at IS NULL',[cid,uid]);await this.pool.execute('UPDATE message_receipts mr JOIN messages m ON m.id=mr.message_id SET mr.delivered_at=COALESCE(mr.delivered_at,CURRENT_TIMESTAMP),mr.read_at=CURRENT_TIMESTAMP WHERE m.conversation_id=? AND mr.user_id=? AND mr.read_at IS NULL',[cid,uid]);return rows;}
  async getMessages(cid,limit=200,viewerId=null){limit=Math.min(500,Number(limit)||200);const [r]=await this.pool.query(`SELECT m.*,u.username,u.avatar_url, CASE WHEN COUNT(mr.user_id)>0 AND SUM(mr.read_at IS NOT NULL)=COUNT(mr.user_id) THEN 'read' WHEN SUM(mr.delivered_at IS NOT NULL)>0 THEN 'delivered' ELSE 'sent' END AS receipt_status FROM messages m JOIN users u ON u.id=m.sender_id LEFT JOIN message_receipts mr ON mr.message_id=m.id WHERE m.conversation_id=? GROUP BY m.id,u.username,u.avatar_url ORDER BY m.id DESC LIMIT ${limit}`,[cid]);return r.reverse().map(x=>({...x,sender:{id:x.sender_id,username:x.username,avatar_url:x.avatar_url}}));}
  async conversationMembers(cid){const [r]=await this.pool.execute('SELECT u.id,u.username,u.email,u.avatar_url,u.bio FROM conversation_members cm JOIN users u ON u.id=cm.user_id WHERE cm.conversation_id=?',[cid]);return r;}
  async conversationMemberDetails(cid){const [r]=await this.pool.execute('SELECT u.id,u.username,u.email,u.avatar_url,u.bio,cm.role FROM conversation_members cm JOIN users u ON u.id=cm.user_id WHERE cm.conversation_id=? ORDER BY (cm.role="admin") DESC,u.username',[cid]);return r;}
  async addConversationMember(cid,adminId,userId){const [a]=await this.pool.execute('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=? AND role="admin"',[cid,adminId]);if(!a[0])throw new Error('ADMIN_REQUIRED');await this.pool.execute('INSERT IGNORE INTO conversation_members(conversation_id,user_id,role) VALUES(?,?,"member")',[cid,userId]);return true;}
  async removeConversationMember(cid,adminId,userId){const [a]=await this.pool.execute('SELECT 1 FROM conversation_members WHERE conversation_id=? AND user_id=? AND role="admin"',[cid,adminId]);if(!a[0])throw new Error('ADMIN_REQUIRED');if(Number(adminId)===Number(userId))throw new Error('USE_LEAVE');await this.pool.execute('DELETE FROM conversation_members WHERE conversation_id=? AND user_id=?',[cid,userId]);return true;}
  async leaveConversation(cid,userId){const [m]=await this.pool.execute('SELECT role FROM conversation_members WHERE conversation_id=? AND user_id=?',[cid,userId]);if(!m[0])return false;if(m[0].role==='admin'){const [o]=await this.pool.execute('SELECT user_id FROM conversation_members WHERE conversation_id=? AND user_id<>? ORDER BY user_id LIMIT 1',[cid,userId]);if(o[0])await this.pool.execute('UPDATE conversation_members SET role="admin" WHERE conversation_id=? AND user_id=?',[cid,o[0].user_id]);}await this.pool.execute('DELETE FROM conversation_members WHERE conversation_id=? AND user_id=?',[cid,userId]);return true;}
  async markConversationNotifications(uid,cid){await this.pool.execute('UPDATE notifications SET is_read=TRUE WHERE user_id=? AND type="message" AND CAST(JSON_UNQUOTE(JSON_EXTRACT(payload,"$.conversationId")) AS UNSIGNED)=?',[uid,cid]);}
  async saveSummary(cid,s){const [r]=await this.pool.execute('INSERT INTO summaries(conversation_id,summary,decisions,action_items,suggestions) VALUES(?,?,?,?,?)',[cid,s.summary,JSON.stringify(s.decisions),JSON.stringify(s.action_items),JSON.stringify(s.suggestions)]);return {id:r.insertId,conversation_id:cid,...s,created_at:new Date()};}
  async summariesForUser(uid){const [r]=await this.pool.execute('SELECT s.* FROM summaries s JOIN conversation_members cm ON cm.conversation_id=s.conversation_id WHERE cm.user_id=? ORDER BY s.created_at DESC',[uid]);return r.map(x=>({...x,decisions:typeof x.decisions==='string'?JSON.parse(x.decisions):x.decisions,action_items:typeof x.action_items==='string'?JSON.parse(x.action_items):x.action_items,suggestions:typeof x.suggestions==='string'?JSON.parse(x.suggestions):x.suggestions}));}
  async addNotification(uid,type,payload){const [r]=await this.pool.execute('INSERT INTO notifications(user_id,type,payload) VALUES(?,?,?)',[uid,type,JSON.stringify(payload)]);return {id:r.insertId,user_id:uid,type,payload,is_read:false,created_at:new Date()};}
  async notifications(uid){const [r]=await this.pool.execute('SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC',[uid]);return r.map(x=>({...x,payload:typeof x.payload==='string'?JSON.parse(x.payload):x.payload}));}
  async markNotifications(uid,types=null){if(Array.isArray(types)&&types.length){const marks=types.map(()=>'?').join(',');await this.pool.execute(`UPDATE notifications SET is_read=TRUE WHERE user_id=? AND type IN (${marks})`,[uid,...types]);}else await this.pool.execute('UPDATE notifications SET is_read=TRUE WHERE user_id=?',[uid]);}
  async addReset(uid,hash,expires){const [r]=await this.pool.execute('INSERT INTO password_resets(user_id,code_hash,expires_at) VALUES(?,?,?)',[uid,hash,new Date(expires)]);return {id:r.insertId,user_id:uid,code_hash:hash,expires_at:expires,used:false};}
  async latestReset(uid){const [r]=await this.pool.execute('SELECT * FROM password_resets WHERE user_id=? AND used=FALSE ORDER BY id DESC LIMIT 1',[uid]);return r[0]||null;}
  async markResetUsed(id){await this.pool.execute('UPDATE password_resets SET used=TRUE WHERE id=?',[id]);}

  async isBlockedEitherWay(a,b){const [r]=await this.pool.execute('SELECT 1 FROM user_blocks WHERE (blocker_id=? AND blocked_user_id=?) OR (blocker_id=? AND blocked_user_id=?) LIMIT 1',[a,b,b,a]);return !!r[0];}
  async blockedIds(uid){const [r]=await this.pool.execute('SELECT blocked_user_id FROM user_blocks WHERE blocker_id=?',[uid]);return r.map(x=>Number(x.blocked_user_id));}
  async blockUser(blocker,blocked){if(Number(blocker)===Number(blocked))throw new Error('SELF');const [u]=await this.pool.execute('SELECT id FROM users WHERE id=? AND status="active"',[blocked]);if(!u[0])throw new Error('USER_NOT_FOUND');await this.pool.execute('INSERT IGNORE INTO user_blocks(blocker_id,blocked_user_id) VALUES(?,?)',[blocker,blocked]);return true;}
  async unblockUser(blocker,blocked){await this.pool.execute('DELETE FROM user_blocks WHERE blocker_id=? AND blocked_user_id=?',[blocker,blocked]);return true;}
  async reportUser(reporter,reported,{reason,description,conversation_id=null,message_id=null}){if(Number(reporter)===Number(reported))throw new Error('SELF');const [u]=await this.pool.execute('SELECT id FROM users WHERE id=?',[reported]);if(!u[0])throw new Error('USER_NOT_FOUND');const [r]=await this.pool.execute('INSERT INTO reports(reporter_id,reported_user_id,conversation_id,message_id,reason,description) VALUES(?,?,?,?,?,?)',[reporter,reported,conversation_id||null,message_id||null,String(reason||'other').slice(0,60),String(description||'').slice(0,1000)]);return {id:r.insertId};}
  async adminReports(){const [r]=await this.pool.query('SELECT r.*,ru.username reporter_username,ru.avatar_url reporter_avatar,tu.username reported_username,tu.email reported_email,tu.avatar_url reported_avatar,tu.status reported_status FROM reports r JOIN users ru ON ru.id=r.reporter_id JOIN users tu ON tu.id=r.reported_user_id ORDER BY r.created_at DESC LIMIT 300');return r;}
  async setReportStatus(id,status,adminEmail){const allowed=['open','reviewed','resolved','dismissed'];if(!allowed.includes(status))throw new Error('INVALID_STATUS');await this.pool.execute('UPDATE reports SET status=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?',[status,adminEmail,id]);const [r]=await this.pool.execute('SELECT * FROM reports WHERE id=?',[id]);return r[0]||null;}
  async setUserStatus(id,status){const allowed=['active','suspended','deleted'];if(!allowed.includes(status))throw new Error('INVALID_STATUS');await this.pool.execute('UPDATE users SET status=? WHERE id=?',[status,id]);return this.getUser(id);}
  async adminStats(){const q=async s=>(await this.pool.query(s))[0][0].n;return {users:await q('SELECT COUNT(*) n FROM users'),activeUsers:await q('SELECT COUNT(*) n FROM users WHERE status="active"'),suspendedUsers:await q('SELECT COUNT(*) n FROM users WHERE status="suspended"'),openReports:await q('SELECT COUNT(*) n FROM reports WHERE status="open"'),friendships:await q('SELECT COUNT(*) n FROM friendships WHERE status="accepted"'),conversations:await q('SELECT COUNT(*) n FROM conversations'),summaries:await q('SELECT COUNT(*) n FROM summaries')};}
  async adminUsers(){const [r]=await this.pool.query('SELECT id,username,email,avatar_url,bio,status,created_at FROM users ORDER BY id DESC');return r;}

  async ensureMeeting(roomId,conversationId=null){const [r]=await this.pool.execute('SELECT * FROM meeting_sessions WHERE room_id=? LIMIT 1',[String(roomId).slice(0,80)]);if(r[0])return r[0];const [x]=await this.pool.execute('INSERT INTO meeting_sessions(room_id,conversation_id) VALUES(?,?)',[String(roomId).slice(0,80),conversationId||null]);return {id:x.insertId,room_id:String(roomId).slice(0,80),conversation_id:conversationId||null,created_at:new Date()};}
  async addMeetingParticipant(meetingId,userId){await this.pool.execute('INSERT IGNORE INTO meeting_participants(meeting_id,user_id) VALUES(?,?)',[meetingId,userId]);return true;}
  async isMeetingParticipant(roomId,userId){const [r]=await this.pool.execute('SELECT 1 FROM meeting_sessions m JOIN meeting_participants p ON p.meeting_id=m.id WHERE m.room_id=? AND p.user_id=? LIMIT 1',[String(roomId),userId]);return !!r[0];}
  async saveMeetingTranscript(roomId,{conversation_id=null,speaker_id,speaker_name,language,text}){const m=await this.ensureMeeting(roomId,conversation_id);const [r]=await this.pool.execute('INSERT INTO meeting_transcripts(meeting_id,speaker_id,speaker_name,language,text) VALUES(?,?,?,?,?)',[m.id,speaker_id,String(speaker_name||'Participant').slice(0,80),String(language||'').slice(0,20),String(text||'').slice(0,2000)]);return {id:r.insertId,meeting_id:m.id,room_id:m.room_id,conversation_id:m.conversation_id,speaker_id,speaker_name,language,text,created_at:new Date()};}
  async meetingTranscript(roomId,userId){if(!(await this.isMeetingParticipant(roomId,userId)))return null;const [r]=await this.pool.execute('SELECT t.*,m.room_id,m.conversation_id FROM meeting_transcripts t JOIN meeting_sessions m ON m.id=t.meeting_id WHERE m.room_id=? ORDER BY t.id',[String(roomId)]);return r;}
  async saveMeetingSummary(roomId,userId,language,s){const [m]=await this.pool.execute('SELECT m.* FROM meeting_sessions m JOIN meeting_participants p ON p.meeting_id=m.id WHERE m.room_id=? AND p.user_id=? LIMIT 1',[String(roomId),userId]);if(!m[0])throw new Error('NOT_ALLOWED');const [r]=await this.pool.execute('INSERT INTO meeting_summaries(meeting_id,requested_by,language,summary,key_points,decisions,action_items,suggestions) VALUES(?,?,?,?,?,?,?,?)',[m[0].id,userId,language,s.summary,JSON.stringify(s.key_points||[]),JSON.stringify(s.decisions||[]),JSON.stringify(s.action_items||[]),JSON.stringify(s.suggestions||[])]);return {id:r.insertId,meeting_id:m[0].id,room_id:m[0].room_id,conversation_id:m[0].conversation_id,requested_by:userId,language,...s,created_at:new Date()};}
  async meetingSummariesForUser(uid){const [r]=await this.pool.execute('SELECT s.*,m.room_id,m.conversation_id FROM meeting_summaries s JOIN meeting_sessions m ON m.id=s.meeting_id JOIN meeting_participants p ON p.meeting_id=m.id WHERE p.user_id=? ORDER BY s.created_at DESC',[uid]);const parse=v=>typeof v==='string'?JSON.parse(v||'[]'):(v||[]);return r.map(x=>({...x,key_points:parse(x.key_points),decisions:parse(x.decisions),action_items:parse(x.action_items),suggestions:parse(x.suggestions)}));}
  async deleteMeetingSummary(id,uid){const [r]=await this.pool.execute('DELETE s FROM meeting_summaries s JOIN meeting_participants p ON p.meeting_id=s.meeting_id WHERE s.id=? AND p.user_id=?',[id,uid]);return r.affectedRows>0;}
  async clearMeetingTranscript(roomId,uid){if(!(await this.isMeetingParticipant(roomId,uid)))return false;await this.pool.execute('DELETE t FROM meeting_transcripts t JOIN meeting_sessions m ON m.id=t.meeting_id WHERE m.room_id=?',[String(roomId)]);return true;}

  async audit(admin_email,action,target_user_id,details){await this.pool.execute('INSERT INTO audit_logs(admin_email,action,target_user_id,details) VALUES(?,?,?,?)',[admin_email,action,target_user_id||null,JSON.stringify(details||{})]);}
}

async function createStore(){
  if((process.env.DB_MODE||'local').toLowerCase()==='mysql'){
    const pool=mysql.createPool({host:process.env.MYSQL_HOST||'127.0.0.1',port:Number(process.env.MYSQL_PORT||3306),user:process.env.MYSQL_USER||'root',password:process.env.MYSQL_PASSWORD||'',database:process.env.MYSQL_DATABASE||'connect',waitForConnections:true,connectionLimit:10});
    await pool.query('SELECT 1'); console.log('Storage: MySQL'); return new MySQLStore(pool);
  }
  console.log('Storage: local JSON demo database'); return new LocalStore(path.join(__dirname,'data','db.json'));
}
module.exports={createStore};
